knp_snappy:
    pdf:
        enabled:    true
        binary:     '/usr/bin/wkhtmltopdf'
        options:
           enable-local-file-access: true
    image:
        enabled:    true
        binary:     '/usr/bin/wkhtmltoimage'
        options:    []
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 20 # In seconds
